name: Update KSU Submodule to Specific Commit

on:
  workflow_dispatch:

jobs:
  update-ksu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: Thankssidex
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PUSH }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"


      - name: Commit and Push Submodule Changes
        run: |
          git add KernelSU-Next
          if git diff --staged --quiet; then
            echo "Submodule is already pointing to commit aa12c9baef15b535ae530fc0b5dc8ede6486be5f"
          else
            git commit -m "submodule: update KernelSU-Next to commit aa12c9baef15b535ae530fc0b5dc8ede6486be5f"
            git push origin Thankssidex
          fi

